[package]
name = "jade_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
# jade_core ={path = "../jade_core"}
ratatui = "0.29.0"

[[example]]
name = "log_widget"
